[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "detect-ships"
version = "0.1.0"
dependencies = ["opencv-python"]

[project.scripts]
detect_ships = "detect_ships:detect_and_save_ships"